= aerospace-move-node-to-monitor(1)
include::util/man-attributes.adoc[]
:manname: aerospace-move-node-to-monitor
// tag::purpose[]
:manpurpose: Move window to monitor targeted by relative direction, by order, or by pattern
// end::purpose[]

// =========================================================== Synopsis
== Synopsis
[verse]
// tag::synopsis[]
aerospace move-node-to-monitor [-h|--help] [--window-id <window-id>] [--focus-follows-window]
                               [--wrap-around] (left|down|up|right|next|prev)
aerospace move-node-to-monitor [-h|--help] [--window-id <window-id>] [--focus-follows-window]
                               [--fail-if-noop] [--] <monitor-pattern>...

// end::synopsis[]

// =========================================================== Description
== Description

// tag::body[]
{manpurpose}

// =========================================================== Options
include::./util/conditional-options-header.adoc[]

-h, --help:: Print help
--wrap-around:: Make it possible to wrap around the movement

--focus-follows-window::
Make sure that the window in question receives focus after moving.
This flag is a shortcut for manually running `aerospace-workspace`/`aerospace-focus` after a successful `move-node-to-monitor` execution.

--fail-if-noop::
Exit with non-zero code if moving the window to the monitor it already belongs to

--window-id <window-id>::
include::./util/window-id-flag-desc.adoc[]

// =========================================================== Arguments
include::util/conditional-arguments-header.adoc[]

(left|down|up|right)::
Move window to monitor in direction relative to the focused monitor

(next|prev)::
Move window to the next|prev monitor in the order they appear in the tray icon

<monitor-pattern>...::
Find the first matching monitor and move the window there.
Multiple monitor patterns are useful for different monitor configurations.
Monitor patterns follow the same format as in the `workspace-to-monitor-force-assignment` config option

// end::body[]

// =========================================================== Footer
include::util/man-footer.adoc[]
